#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr

bspc monitor -d web terminal book vm work social email misc

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding		15

bspc config split_ratio		0.52
bspc config borderless_monocle	true
bspc config gapless_monocle	true
bspc config ignore_ewmh_struts	true

# launch on startup
$HOME/.config/polybar/launch.sh
/usr/bin/dunst &
/usr/bin/thunderbird &

# rules
bspc rule -a firefox desktop='^1#focused:'
bspc rule -a Alacritty desktop='^2#focused:'
bspc rule -a Evince desktop='^3#focused:'
bspc rule -a "VirtualBox Manager" desktop='^4#focused:'
bspc rule -a "VirtualBox Machine" desktop='^4#focused:'
bspc rule -a "Microsoft Teams - Preview" desktop='^5#focused:'
bspc rule -a discord desktop='^6#focused:'
bspc rule -a Thunderbird desktop='^7#focused:'
bspc rule -a qBittorrent desktop='^8#focused:'

# env
export _JAVA_AWT_WM_NONREPARENTING=1
